### PR TITLE
Include Avisynth+ headers and libraries for out-of-the-box x64 compilation.

### PR DESCRIPTION
**Pull request by Zinfidel**
Also updated submodules and removed an extraneous reference.

### CODE REVIEW

**Comment by vadosnaprimer** [comment]
Will this work with regular avisynth?

**Comment by Zinfidel** [comment]
> Will this work with regular avisynth?

Probably not. According to this line in the avisynth+ c header file:
```
// NOTE: this is a partial update of the Avisynth C interface to recognize
// new color spaces added in Avisynth 2.60. By no means is this document
// completely Avisynth 2.60 compliant
```
and the notes on on https://github.com/pinterf/assrender/releases/ it sounds like it will become at least partially incompatible with regular Avisynth.

**Comment by vadosnaprimer** [comment]
Oh yeah I trust pinterf much better than myself so we may consider my fork obsolete at this point.

**Comment by Zinfidel** [comment]
> Oh yeah I trust pinterf much better than myself so we may consider my fork obsolete at this point.

Likewise for mine.

**Pull request closed without merging**
